version: "2"
services:
      
      mongo:
        container_name: mongodb
        image: mongo
        
        ports:
        - "27017:27017"
      cassandra:
        container_name: cassandradb
        image: cassandra:2.2.11
        ports:
        - 9042:9042
      app:
        container_name: app
        restart: always
        build: .
        ports:
        - "4200:4200"
        depends_on: 
        - mongo
        - cassandra



