version: "2"
services:
      app:
        container_name: app
        restart: always
        build: .
        ports:
        - "4200:4200"
        links: 
        - mongo
      mongo:
        container_name: mongo
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - "27017:27017"

